### ISSUE TITLE
Digging out of Technical Debt

### ISSUE THREAD

**Issue by 0xFC963F18DC21** [0xFC963F18DC21/ModePile#10]
This codebase is in need of a massive refactor. Not only for better-looking code, but also for (possibly) better performance by removing unnecessary operations and the like.

## Notes

Any changes must be compatible with Java 8, as this is what the game uses.

## TODO

- [ ] Libraries
  - [ ] Removing excess reflection calls.
  - [ ] Removing useless / redundant code.
  - [ ] Refactoring the public API. 
- [ ] Modes
  - [ ] General optimisations.
  - [ ] Cleanup of repeated code.
  - [ ] Possible abstraction of Finite State Machine pattern used to control the modes.

**Comment by KirbyJoe** [comment]
I want to ask a question: Why is development for ModePile active again?

**Comment by 0xFC963F18DC21** [comment]
> I want to ask a question: Why is development for ModePile active again?

I wouldn't really call it "active", more "might do something occasionally with this to slowly clean it up, then maybe (but unlikely) other things later".
